export { default as ConfirmDialog } from './ConfirmDialog.vue'
export { default as AlertDialog } from './AlertDialog.vue'
export { useConfirm } from './use-confirm'
export { useAlert } from './use-alert'
export type { ConfirmDialogProps, AlertDialogProps, DialogColor } from './types'
